### ISSUE TITLE
build-files & howto missing

### ISSUE THREAD

**Issue by frehberg** [GBert/railroad#1]
Hello,

I tried to build a fresh checkout, but the build failes immediatly. It seems some files of the build-framework (make) have not been committed yet.

The file  $(TOPDIR)/rules.mk missing 
The file  $(INCLUDE_DIR)/package.mk missing, too.
For example, these file are referenced by ./can2udp/Makefile.

Please commit the missing  files to the repo, and please add a short howto of the required environment variables.

Cu, Frank

**Comment by GBert** [comment]
Sorry, for the late response.
To top Makefile is for OpenWRT. If you want to build it under other environments, change into the 'src' directory. 'make' should work without any problem
