### ISSUE TITLE
S88 Rückmelder & Waveshare 2-CH CAN HAT in RailControl nutzen?

### ISSUE THREAD

**Issue by AgentSmith0** [GBert/railroad#11]
Guten Tag,
ist es möglich einen S88 Rückmelder an das Waveshare 17912 CAN Modul anzuschließen und mit Ihren bereitgestellten Programmen in RailControl zu nutzen?

**Comment by DB-59** [comment]
Hallo AgentSmith, im RailControl-Forum hatte ich den RailPi vorgestellt. alle Fragen hierzu beantworte ich Dir gern.

Momentan bin ich unterwegs und bzgl der Kommunikation etwas eingeschränkt. Bitte stelle Deine Fragen hierzu auch ins RailControlForum, dort kannst Du mich via eMail such direkt kontaktieren (User _db_)

Viele Grüße, Detlef

**Comment by DB-59** [comment]
Sorry, mein UserNsme im RailControl-Forum lautet _DB_

**Comment by DB-59** [comment]
Hoppla - die Unterstriche werden nicht geschrieben:
unterstrichDBunterstrich
muss es heißen…
