### ISSUE TITLE
TCP-read  may cause erroneous message

### ISSUE THREAD

**Issue by frehberg** [GBert/railroad#2]
Hello,

The following line reads a bunch of bytes from TCP-connection.

 if ((n = read(tcp_socket, netframe, MAXDG)) == 0) {

The following code does not verify, if the read bytes represent a complete/single message, but forwards directly to CAN-socket.

Using TCP, it may happen, that the read-function returns with too little or too many bytes (for example only a fragment of the intended message or  also the first bytes of next message in stream)
(Does not happen with message oriented UDP) 

In this use-case, if the short messages are sent with high frequency via TCP, it is very likely that the TCP-reader in can2lan might read over the boundary of a single message, forwarding faulty messages to the Can-bus. 

To solve the issue, the TCP-reader must verify that the read bytes match exactly one message. 
For example the TCP-reader could read till the 5th byte udpframe[4] , defining the payload length N (DLC), and then continue reading the corresponding N bytes of the payload.

Cu, Frank

**Comment by GBert** [comment]
many thx for your suggestion. I will check it and look for a solution ...

**Comment by GBert** [comment]
you are right but I've never seen  n % 13 != 0.
