### ISSUE TITLE
When 8 bytes CAN Frame is sent, the output is not coming properly on CAN interface

### ISSUE THREAD

**Issue by supersports999** [GBert/railroad#3]
In the current program implementation you are sending 4bytes can frame & incrementing the DATA.. 
Say,

can0  07B   [4]  00 00 00 01
can0  07B   [4]  00 00 00 02
can0  07B   [4]  00 00 00 03

& so on..

When i changed the frame length to 8 bytes the output is coming as below

can0  07B   [8]  00 00 00 01 01 00 00 00
can0  07B   [8]  00 00 00 02 02 00 00 00
can0  07B   [8]  00 00 00 03 03 00 00 00

**_I expect the output as below_**

can0  07B   [8]  00 00 00 00 00 00 00 01
can0  07B   [8]  00 00 00 00 00 00 00 02
can0  07B   [8]  00 00 00 00 00 00 00 03

Please let me know what changes need to be done in the current program to get the desired output as mentioned above.

**Comment by GBert** [comment]
Please Show me your code. Do you use can2eth ?

**Comment by GBert** [comment]
Could you shwo me your code, please ?
Do you use can2eth ? All other code here is M*rklin secific ...
